import {
  assertValidAgentHierarchy,
  type AgentRoleContract,
  type AgentSkillManifest,
  type AgentDepartmentId,
  type AgentRiskLevel,
} from "@eauto/domain";

const GLOBAL_FORBIDDEN = Object.freeze([
  "marketplace.write-unapproved",
  "money.transfer",
  "credential.read",
  "policy.bypass",
  "evidence.fabricate",
  "memory-as-operational-truth",
]);

export const AGENT_SKILL_CATALOG: readonly AgentSkillManifest[] = Object.freeze([
  skill(
    "evidence-analysis",
    "1.0.0",
    "Análisis de evidencia",
    "Normaliza evidencia, procedencia, frescura e incertidumbre.",
    "low",
    ["evidence.read", "evidence.package"],
    [],
    ["source-provenance"],
    false,
    "global-stable",
  ),
  skill(
    "economic-truth",
    "1.0.0",
    "Verdad económica",
    "Calcula rentabilidad únicamente desde costos y órdenes verificadas.",
    "high",
    ["economics.read", "economics.recompute", "proposal.create"],
    ["economics.estimate-missing"],
    ["order-snapshot", "cost-evidence"],
    true,
    "agent-versioned",
  ),
  skill(
    "portfolio-analysis",
    "1.0.0",
    "Análisis de portafolio",
    "Clasifica productos con ciclo de vida, stock, ventas y evidencia de temporada.",
    "medium",
    ["portfolio.read", "proposal.create"],
    ["listing.write"],
    ["listing-snapshot", "economic-snapshot"],
    false,
    "agent-versioned",
  ),
  skill(
    "catalog-research",
    "1.0.0",
    "Investigación de catálogo",
    "Identifica productos, atributos, competencia y oportunidades sin publicar.",
    "medium",
    ["catalog.read", "research.read", "proposal.create"],
    ["listing.write", "supplier.purchase"],
    ["product-source", "market-evidence"],
    false,
    "agent-versioned",
  ),
  skill(
    "supplier-analysis",
    "1.0.0",
    "Proveedores y abastecimiento",
    "Evalúa costo, disponibilidad, lead time y concentración de proveedor.",
    "high",
    ["supplier.read", "inventory.read", "proposal.create"],
    ["supplier.purchase", "inventory.write"],
    ["supplier-evidence", "inventory-snapshot"],
    true,
    "agent-versioned",
  ),
  skill(
    "customer-operations",
    "1.0.0",
    "Operación y atención",
    "Prioriza órdenes, preguntas, reclamos, reputación y SLA.",
    "high",
    ["orders.read", "questions.read", "claims.read", "proposal.create"],
    ["question.reply", "claim.intervene", "order.cancel"],
    ["customer-operation-snapshot"],
    true,
    "agent-versioned",
  ),
  skill(
    "content-production",
    "1.0.0",
    "Producción de contenido",
    "Prepara assets, copy y variantes con trazabilidad y revisión.",
    "medium",
    ["content.read", "content.draft", "proposal.create"],
    ["content.publish"],
    ["product-evidence", "brand-policy"],
    true,
    "agent-versioned",
  ),
  skill(
    "product-launch",
    "1.0.0",
    "Lanzamiento de producto",
    "Orquesta identificación, economía, contenido y preview antes de publicación.",
    "high",
    ["catalog.read", "content.draft", "economics.read", "proposal.create"],
    ["listing.write"],
    ["product-identity", "economic-snapshot", "content-assets"],
    true,
    "agent-versioned",
  ),
  skill(
    "ads-analysis",
    "1.0.0",
    "Rentabilidad publicitaria",
    "Evalúa campañas, gasto, atribución y retorno sin modificar Ads.",
    "high",
    ["ads.read", "economics.read", "proposal.create"],
    ["ads.write", "budget.spend"],
    ["ads-snapshot", "economic-snapshot"],
    true,
    "agent-versioned",
  ),
  skill(
    "web-channel",
    "1.0.0",
    "Canal ecommerce propio",
    "Audita catálogo, SEO, performance y planes de storefront.",
    "medium",
    ["web.read", "web.plan", "proposal.create"],
    ["web.deploy", "web.write"],
    ["web-health", "catalog-snapshot"],
    true,
    "agent-versioned",
  ),
  skill(
    "governance-review",
    "1.0.0",
    "Gobernanza y revisión",
    "Evalúa políticas, autonomía, riesgo, evidencia y cumplimiento.",
    "critical",
    ["policy.read", "receipts.read", "review.create"],
    ["action.execute", "review-own-proposal"],
    ["policy-version", "receipt-chain"],
    true,
    "global-stable",
  ),
  skill(
    "memory-learning",
    "1.0.0",
    "Memoria y aprendizaje",
    "Admite aprendizajes consultivos desde outcomes verificados.",
    "medium",
    ["memory.read", "memory.propose", "outcomes.read"],
    ["memory-operational-write", "autonomy.promote"],
    ["verified-outcome"],
    true,
    "agent-versioned",
  ),
  skill(
    "research",
    "1.0.0",
    "Investigación",
    "Produce evidencia acotada con fuentes y stop rules.",
    "medium",
    ["research.read", "evidence.package"],
    ["action.execute"],
    ["research-question"],
    false,
    "task-volatile",
  ),
  skill(
    "experimentation",
    "1.0.0",
    "Experimentación",
    "Diseña experimentos reversibles, criterios y rollback.",
    "high",
    ["experiment.plan", "outcomes.read", "proposal.create"],
    ["experiment.activate", "experiment.rollback"],
    ["baseline-evidence", "success-criteria"],
    true,
    "agent-versioned",
  ),
]);

const specialists: readonly AgentRoleContract[] = Object.freeze([
  specialist(
    "economic-ingestion",
    "Ingesta económica",
    "finance-director",
    "finance",
    "Normalizar órdenes, costos y reconciliaciones con procedencia.",
    ["orders.read", "economics.read"],
    ["economic-snapshot"],
    ["order-snapshot", "cost-evidence"],
    ["evidence-analysis", "economic-truth"],
    "high",
  ),
  specialist(
    "unit-economics",
    "Unit Economics",
    "finance-director",
    "finance",
    "Determinar contribución, margen y capital por producto y orden.",
    ["economics.read", "portfolio.read", "proposal.create"],
    ["profit-report", "margin-risk"],
    ["economic-snapshot"],
    ["economic-truth"],
    "high",
  ),
  specialist(
    "pricing",
    "Pricing",
    "finance-director",
    "finance",
    "Proponer precios con margen mínimo, competencia y riesgo.",
    ["economics.read", "catalog.read", "proposal.create"],
    ["pricing-proposal"],
    ["economic-snapshot", "market-evidence"],
    ["economic-truth", "catalog-research"],
    "high",
  ),
  specialist(
    "ads-profitability",
    "Rentabilidad Ads",
    "finance-director",
    "finance",
    "Evaluar gasto publicitario, atribución y retorno por producto.",
    ["ads.read", "economics.read", "proposal.create"],
    ["ads-profitability-report"],
    ["ads-snapshot", "economic-snapshot"],
    ["ads-analysis", "economic-truth"],
    "high",
  ),

  specialist(
    "analytics",
    "Analytics",
    "portfolio-director",
    "portfolio",
    "Generar reportes de ventas, visitas, conversión y anomalías.",
    ["analytics.read", "portfolio.read"],
    ["analytics-report"],
    ["analytics-snapshot"],
    ["evidence-analysis", "portfolio-analysis"],
    "low",
  ),
  specialist(
    "catalog",
    "Catálogo",
    "portfolio-director",
    "portfolio",
    "Auditar atributos, categorías, duplicados y brechas del catálogo.",
    ["catalog.read", "proposal.create"],
    ["catalog-report"],
    ["listing-snapshot"],
    ["catalog-research"],
    "medium",
  ),
  specialist(
    "product-research",
    "Investigación de producto",
    "portfolio-director",
    "portfolio",
    "Descubrir y comparar oportunidades de producto con evidencia.",
    ["research.read", "catalog.read", "proposal.create"],
    ["product-opportunity"],
    ["market-evidence", "supplier-evidence"],
    ["catalog-research", "research"],
    "medium",
  ),
  specialist(
    "listing-retread",
    "Renovación de publicaciones",
    "portfolio-director",
    "portfolio",
    "Preparar planes de mejora para publicaciones estancadas.",
    ["catalog.read", "analytics.read", "content.read", "proposal.create"],
    ["retread-plan"],
    ["listing-snapshot", "analytics-snapshot"],
    ["portfolio-analysis", "content-production"],
    "medium",
  ),

  specialist(
    "supplier-manager",
    "Proveedores",
    "supply-director",
    "supply",
    "Evaluar proveedores, costos, lead time, calidad y concentración.",
    ["supplier.read", "proposal.create"],
    ["supplier-report"],
    ["supplier-evidence"],
    ["supplier-analysis"],
    "high",
  ),
  specialist(
    "inventory-forecast",
    "Inventario y forecast",
    "supply-director",
    "supply",
    "Predecir quiebres, exceso y reposición usando datos verificados.",
    ["inventory.read", "orders.read", "proposal.create"],
    ["inventory-forecast"],
    ["inventory-snapshot", "order-snapshot"],
    ["supplier-analysis", "evidence-analysis"],
    "high",
  ),
  specialist(
    "acquisition-imports",
    "Compras e importaciones",
    "supply-director",
    "supply",
    "Evaluar landed cost, flete, aduana y capital inmovilizado.",
    ["supplier.read", "economics.read", "proposal.create"],
    ["acquisition-proposal"],
    ["supplier-evidence", "landed-cost-evidence"],
    ["supplier-analysis", "economic-truth"],
    "critical",
  ),

  specialist(
    "sales-service",
    "Ventas y preguntas",
    "operations-director",
    "operations",
    "Priorizar ventas, preguntas pendientes y conversión sin responder automáticamente.",
    ["orders.read", "questions.read", "proposal.create"],
    ["sales-service-brief"],
    ["customer-operation-snapshot"],
    ["customer-operations"],
    "high",
  ),
  specialist(
    "claims-reputation",
    "Reclamos y reputación",
    "operations-director",
    "operations",
    "Detectar riesgos de reclamo, devolución y reputación.",
    ["claims.read", "reputation.read", "proposal.create"],
    ["reputation-risk-brief"],
    ["customer-operation-snapshot"],
    ["customer-operations"],
    "critical",
  ),
  specialist(
    "shipping-logistics",
    "Despacho y logística",
    "operations-director",
    "operations",
    "Auditar entregas, SLA, tracking y fallas de transporte.",
    ["shipping.read", "orders.read", "proposal.create"],
    ["shipping-audit"],
    ["shipment-snapshot"],
    ["customer-operations", "evidence-analysis"],
    "high",
  ),

  specialist(
    "product-recognition",
    "Reconocimiento de producto",
    "growth-director",
    "growth",
    "Identificar productos y atributos desde fotografías y fuentes verificadas.",
    ["content.read", "catalog.read", "research.read"],
    ["product-identity"],
    ["source-image", "market-evidence"],
    ["catalog-research"],
    "medium",
  ),
  specialist(
    "product-launch",
    "Lanzamiento",
    "growth-director",
    "growth",
    "Preparar el lanzamiento completo con economía, contenido y preview.",
    ["catalog.read", "content.draft", "economics.read", "proposal.create"],
    ["launch-package"],
    ["product-identity", "economic-snapshot", "content-assets"],
    ["product-launch"],
    "high",
  ),
  specialist(
    "creative-studio",
    "Creative Studio",
    "growth-director",
    "growth",
    "Coordinar assets y variantes comerciales con brand policy.",
    ["content.read", "content.draft"],
    ["creative-package"],
    ["product-evidence", "brand-policy"],
    ["content-production"],
    "medium",
  ),
  specialist(
    "image-production",
    "Imágenes",
    "growth-director",
    "growth",
    "Preparar, mejorar y evaluar imágenes fieles al producto.",
    ["content.read", "content.draft"],
    ["image-assets"],
    ["source-image", "brand-policy"],
    ["content-production"],
    "medium",
  ),
  specialist(
    "video-production",
    "Video",
    "growth-director",
    "growth",
    "Preparar guiones y video comercial por canal con licencias trazables.",
    ["content.read", "content.draft"],
    ["video-assets"],
    ["product-evidence", "brand-policy"],
    ["content-production"],
    "medium",
  ),
  specialist(
    "copy-social",
    "Copy y redes",
    "growth-director",
    "growth",
    "Crear copy, guiones y calendario social sin publicar automáticamente.",
    ["content.read", "content.draft"],
    ["copy-package"],
    ["product-evidence", "brand-policy"],
    ["content-production"],
    "medium",
  ),
  specialist(
    "product-ads",
    "Product Ads",
    "growth-director",
    "growth",
    "Analizar campañas y preparar propuestas de optimización con rentabilidad.",
    ["ads.read", "economics.read", "proposal.create"],
    ["ads-proposal"],
    ["ads-snapshot", "economic-snapshot"],
    ["ads-analysis"],
    "high",
  ),

  specialist(
    "owned-ecommerce",
    "Ecommerce propio",
    "expansion-director",
    "expansion",
    "Auditar y planificar catálogo, SEO, checkout y performance del canal propio.",
    ["web.read", "catalog.read", "proposal.create"],
    ["web-channel-plan"],
    ["web-health", "catalog-snapshot"],
    ["web-channel"],
    "high",
  ),
  specialist(
    "marketplace-expansion",
    "Expansión de marketplaces",
    "expansion-director",
    "expansion",
    "Evaluar canales nuevos por costo, riesgo, requisitos y retorno.",
    ["research.read", "economics.read", "proposal.create"],
    ["channel-expansion-brief"],
    ["market-evidence", "economic-snapshot"],
    ["research", "economic-truth"],
    "critical",
  ),

  specialist(
    "memory-learning",
    "Memoria y aprendizaje",
    "governance-director",
    "governance",
    "Admitir aprendizajes consultivos desde outcomes verificados.",
    ["memory.read", "outcomes.read", "memory.propose"],
    ["learning-candidate"],
    ["verified-outcome"],
    ["memory-learning"],
    "high",
  ),
  specialist(
    "research",
    "Investigación",
    "governance-director",
    "governance",
    "Investigar preguntas acotadas y producir paquetes de evidencia.",
    ["research.read", "evidence.package"],
    ["research-evidence"],
    ["research-question"],
    ["research", "evidence-analysis"],
    "medium",
  ),
  specialist(
    "experimentation",
    "Experimentación",
    "governance-director",
    "governance",
    "Diseñar experimentos reversibles y evaluar outcomes.",
    ["experiment.plan", "outcomes.read", "proposal.create"],
    ["experiment-plan"],
    ["baseline-evidence", "success-criteria"],
    ["experimentation"],
    "high",
  ),
  specialist(
    "risk-compliance",
    "Riesgo y cumplimiento",
    "governance-director",
    "governance",
    "Bloquear propuestas que violen políticas, scope o evidencia.",
    ["policy.read", "receipts.read", "review.create"],
    ["risk-review"],
    ["policy-version", "receipt-chain"],
    ["governance-review"],
    "critical",
  ),
  specialist(
    "critic-auditor",
    "Crítico independiente",
    "governance-director",
    "governance",
    "Buscar evidencia contraria sin modificar la propuesta evaluada.",
    ["evidence.read", "review.create"],
    ["adversarial-review"],
    ["proposal-hash", "evidence-bundle"],
    ["governance-review", "evidence-analysis"],
    "critical",
  ),
  specialist(
    "agent-evaluator",
    "Evaluador de agentes",
    "governance-director",
    "governance",
    "Calcular scorecards, costo, outcomes y elegibilidad de autonomía.",
    ["scorecards.read", "outcomes.read", "receipts.read"],
    ["agent-scorecard"],
    ["verified-outcome", "receipt-chain"],
    ["governance-review"],
    "critical",
  ),
]);

const directors: readonly AgentRoleContract[] = Object.freeze([
  director(
    "finance-director",
    "Director financiero",
    "finance",
    "Proteger la verdad económica, caja, margen y retorno sobre capital.",
    ["economic-ingestion", "unit-economics", "pricing", "ads-profitability"],
  ),
  director(
    "portfolio-director",
    "Director de portafolio",
    "portfolio",
    "Decidir qué impulsar, corregir, experimentar, liquidar o abandonar.",
    ["analytics", "catalog", "product-research", "listing-retread"],
  ),
  director(
    "supply-director",
    "Director de abastecimiento",
    "supply",
    "Gestionar inventario, proveedores, compras, forecast e importaciones.",
    ["supplier-manager", "inventory-forecast", "acquisition-imports"],
  ),
  director(
    "operations-director",
    "Director de operaciones",
    "operations",
    "Proteger pedidos, SLA, atención, reclamos, logística y reputación.",
    ["sales-service", "claims-reputation", "shipping-logistics"],
  ),
  director(
    "growth-director",
    "Director de crecimiento y contenido",
    "growth",
    "Coordinar lanzamientos, creatividad, contenido y publicidad rentable.",
    [
      "product-recognition",
      "product-launch",
      "creative-studio",
      "image-production",
      "video-production",
      "copy-social",
      "product-ads",
    ],
  ),
  director(
    "expansion-director",
    "Director de expansión",
    "expansion",
    "Evaluar ecommerce propio y nuevos marketplaces sin duplicar dominio.",
    ["owned-ecommerce", "marketplace-expansion"],
  ),
  director(
    "governance-director",
    "Director de gobernanza",
    "governance",
    "Controlar política, memoria, investigación, experimentos, auditoría y autonomía.",
    [
      "memory-learning",
      "research",
      "experimentation",
      "risk-compliance",
      "critic-auditor",
      "agent-evaluator",
    ],
  ),
]);

const ceo: AgentRoleContract = Object.freeze({
  id: "ceo",
  version: "1.0.0",
  label: "CEO Agent",
  level: "ceo",
  departmentId: "executive",
  parentAgentId: null,
  mission:
    "Traducir objetivos del CEO humano en planes acotados, delegar a directores y sintetizar decisiones verificables.",
  inputs: Object.freeze(["owner-objective", "company-state", "policy-version"]),
  outputs: Object.freeze(["agent-plan", "ceo-brief", "clarification-request"]),
  requiredEvidenceKinds: Object.freeze(["company-state", "policy-version"]),
  allowedCapabilities: Object.freeze([
    "plan.create",
    "work-order.create",
    "evidence.request",
    "brief.create",
  ]),
  forbiddenCapabilities: GLOBAL_FORBIDDEN,
  skillIds: Object.freeze(["evidence-analysis", "governance-review"]),
  defaultAutonomy: "ask",
  riskLevel: "critical",
  maximumIterations: 5,
  timeoutMs: 120_000,
  maximumDailyBudgetMinorClp: 100_000,
  stablePromptVersion: "ceo-v1",
  active: true,
});

export const COMPANY_AGENT_CATALOG: readonly AgentRoleContract[] = Object.freeze([
  ceo,
  ...directors,
  ...specialists,
]);

assertValidAgentHierarchy(COMPANY_AGENT_CATALOG);

export function getCompanyAgentContract(agentId: string): AgentRoleContract | undefined {
  return COMPANY_AGENT_CATALOG.find((contract) => contract.id === agentId);
}

export function listDepartmentAgents(
  departmentId: AgentDepartmentId,
): readonly AgentRoleContract[] {
  return COMPANY_AGENT_CATALOG.filter((contract) => contract.departmentId === departmentId);
}

function skill(
  id: string,
  version: string,
  label: string,
  description: string,
  riskLevel: AgentRiskLevel,
  allowedCapabilities: readonly string[],
  forbiddenCapabilities: readonly string[],
  requiredEvidenceKinds: readonly string[],
  requiresHumanApproval: boolean,
  cacheClass: AgentSkillManifest["cacheClass"],
): AgentSkillManifest {
  return Object.freeze({
    id,
    version,
    label,
    description,
    riskLevel,
    allowedCapabilities: Object.freeze([...allowedCapabilities]),
    forbiddenCapabilities: Object.freeze([...forbiddenCapabilities, ...GLOBAL_FORBIDDEN]),
    requiredEvidenceKinds: Object.freeze([...requiredEvidenceKinds]),
    maximumIterations: 5,
    timeoutMs: 120_000,
    requiresHumanApproval,
    cacheClass,
  });
}

function director(
  id: string,
  label: string,
  departmentId: Exclude<AgentDepartmentId, "executive">,
  mission: string,
  outputs: readonly string[],
): AgentRoleContract {
  return Object.freeze({
    id,
    version: "1.0.0",
    label,
    level: "director",
    departmentId,
    parentAgentId: "ceo",
    mission,
    inputs: Object.freeze(["objective", "account-state", "evidence-bundle"]),
    outputs: Object.freeze([...outputs, "director-brief"]),
    requiredEvidenceKinds: Object.freeze(["account-state", "policy-version"]),
    allowedCapabilities: Object.freeze([
      "plan.create",
      "evidence.request",
      "proposal.create",
      "brief.create",
    ]),
    forbiddenCapabilities: GLOBAL_FORBIDDEN,
    skillIds: Object.freeze(["evidence-analysis", "governance-review"]),
    defaultAutonomy: "ask",
    riskLevel: "high",
    maximumIterations: 5,
    timeoutMs: 120_000,
    maximumDailyBudgetMinorClp: 25_000,
    stablePromptVersion: `${id}-v1`,
    active: true,
  });
}

function specialist(
  id: string,
  label: string,
  parentAgentId: string,
  departmentId: Exclude<AgentDepartmentId, "executive">,
  mission: string,
  allowedCapabilities: readonly string[],
  outputs: readonly string[],
  requiredEvidenceKinds: readonly string[],
  skillIds: readonly string[],
  riskLevel: AgentRiskLevel,
): AgentRoleContract {
  return Object.freeze({
    id,
    version: "1.0.0",
    label,
    level: "specialist",
    departmentId,
    parentAgentId,
    mission,
    inputs: Object.freeze(["work-order", "evidence-bundle", "policy-version"]),
    outputs: Object.freeze([...outputs]),
    requiredEvidenceKinds: Object.freeze([...requiredEvidenceKinds]),
    allowedCapabilities: Object.freeze([...allowedCapabilities]),
    forbiddenCapabilities: GLOBAL_FORBIDDEN,
    skillIds: Object.freeze([...skillIds]),
    defaultAutonomy: "ask",
    riskLevel,
    maximumIterations: 4,
    timeoutMs: 90_000,
    maximumDailyBudgetMinorClp: 10_000,
    stablePromptVersion: `${id}-v1`,
    active: true,
  });
}
